# Generated by Django 6.0.5 on 2026-07-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('telebirr', 'Telebirr'), ('cbe', 'CBE'), ('boa', 'BOA'), ('awash', 'Awash'), ('other', 'Other')], help_text='Payment method used (CBE, Telebirr, etc.)', max_length=20, null=True),
        ),
    ]
